# -*- coding: utf-8 -*-
"""Mini_Kinya_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BTxTXLx9R6rtHE8dkSbNeyNiGPo6hqD
"""

# Install required libraries while allowing NumPy 2.x
!apt-get -y install sox
!pip install --upgrade pip --quiet
!pip install nemo_toolkit['asr'] pydub --upgrade --quiet
# Downgrade NumPy and restart runtime to avoid incompatibility with NeMo
!pip install numpy==1.26.4 --quiet
import os
os.kill(os.getpid(), 9)  # Restart the Colab runtime

# Hugging Face authentication and NeMo model load
from google.colab import userdata
from huggingface_hub import login
from nemo.collections import asr as nemo_asr
from pydub import AudioSegment

login(userdata.get('accessmodel'))

hf_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained(
    model_name="mbazaNLP/Kinyarwanda_nemo_stt_conformer_model"
)

class Transcriber:
    def __init__(self, audio_file: str) -> None:
        self.original_audio = audio_file
        self.processed_audio = self.convert_wav_to_16bit_mono()
        self.transcription = self.transcribe()

    def convert_wav_to_16bit_mono(self) -> str:
        try:
            output_file = "/content/processed_audio.wav"
            AudioSegment.from_file(self.original_audio) \
                .set_channels(1) \
                .set_sample_width(2) \
                .set_frame_rate(16000) \
                .export(output_file, format="wav")
            return output_file
        except Exception as e:
            print(f"Error converting audio: {e}")
            return self.original_audio  # Fallback

    def transcribe(self):
        try:
            result = hf_model.transcribe([self.processed_audio])
            return result[0]
        except Exception as e:
            print(f"Error transcribing audio: {e}")
            return "Unable to transcribe audio!"

# Usage
audio_file = "/content/rw-test01.wav"  # Actual uploaded file
transcriber = Transcriber(audio_file)
print("Transcription:", transcriber.transcription)

# Kinyarwanda QA pairs
qa_pairs = {
    "Witwa nde?": "Nitwa ChatGPT.",
    "Utuye he?": "Ntuye kuri interineti, sinfite aho mba nyakuri.",
    "Ufasha gute?": "Nshobora kugufasha gusobanukirwa ibintu, guhindura indimi, kwandika inyandiko, n'ibindi byinshi.",
    "Ni hehe Kigali iherereye?": "Kigali iherereye mu burasirazuba bw’igihugu cya Rwanda.",
    "Ni gute waba mwiza mu ishuri?": "Ugomba kwiga cyane, kumva abarimu, no gusaba ubufasha igihe cyose ukeneye."
}

# Simple matching function
def match_question(user_input):
    for question in qa_pairs:
        if user_input.lower().strip() in question.lower():
            return qa_pairs[question]
    return "Mbabarira, sinasubiza icyo kibazo neza."

# Ask a question in Kinyarwanda
user_input = input("Andika ikibazo cyawe mu Kinyarwanda: ")
response = match_question(user_input)
print("Igisubizo:", response)

!pip install fuzzywuzzy[speedup]

from fuzzywuzzy import process

# Step 1: Create your Kinyarwanda Q&A dictionary
qa_dict = {
    "umeze neza?": "Yego, Ndashima Imana na Allah",
    "Ukorera he?": "Nkorera ku muyoboro wa interineti, sinshobora kugira aho mba.",
    "Ushobora kumfasha gukora ubushakashatsi?": "Yego, mbwira icyo ukeneye kumenya.",
    "Ni iki ChatGPT ishoboye?": "ChatGPT ishobora kugufasha mu bisubizo, ubusobanuro, no gutanga ubufasha kuri gahunda zitandukanye.",
    "Ni gute natsinda amasomo?": "Gira gahunda ihamye yo kwiga, subiramo kenshi kandi usabe ubufasha igihe cyose ukeneye."
}

# Step 2: Ask a user question
user_question = input("Ishyiremo ikibazo cyawe mu Kinyarwanda: ")

# Step 3: Use fuzzy matching to find best match
best_match, score = process.extractOne(user_question, qa_dict.keys())

# Step 4: Set a minimum confidence threshold
if score > 70:  # You can adjust this value
    print("➡️ Igisubizo:", qa_dict[best_match])
else:
    print("🤖 Sory, sinashoboye kumenya icyo ushaka. Gerageza kongera uko ubaza.")

!pip install TTS
!pip install huggingface_hub

from huggingface_hub import login

# This will prompt you to paste your Hugging Face token
login()

# Custom TTS Solution using pretrained models compatible with Google Colab
# Install necessary packages
!pip install -q pydub gTTS langid pytorch_lightning

import os
import torch
import langid
from gtts import gTTS
from IPython.display import Audio, display
import json
from huggingface_hub import hf_hub_download
import numpy as np

class TTSWrapper:
    """
    A wrapper class for different text-to-speech solutions
    """
    def __init__(self):
        self.detect_language = True
        print("TTS Wrapper initialized")

    def synthesize(self, text, lang=None, output_path=None):
        """
        Synthesize speech from text using the appropriate method based on language
        """
        if not lang and self.detect_language:
            # Detect language if not provided
            detected_lang, _ = langid.classify(text)
            lang = detected_lang
            print(f"Detected language: {lang}")

        # Default to English if no language is specified
        if not lang:
            lang = 'en'

        # Use gTTS for most languages
        print(f"Synthesizing text using gTTS: '{text}'")

        # Special handling for Kinyarwanda which might not be directly supported by gTTS
        if lang.lower() in ['rw', 'kinyarwanda']:
            print("Kinyarwanda detected, using closest available language approximation")
            # Use a related language like Swahili as fallback
            tts = gTTS(text=text, lang='sw', slow=False)
        else:
            # For other languages, use default gTTS behavior
            try:
                tts = gTTS(text=text, lang=lang, slow=False)
            except:
                print(f"Language {lang} not supported by gTTS, falling back to English")
                tts = gTTS(text=text, lang='en', slow=False)

        # Save audio file
        if not output_path:
            output_path = "/content/tts_output.mp3"
        tts.save(output_path)
        print(f"Audio saved to {output_path}")

        # Convert to wav if needed
        if output_path.endswith(".mp3"):
            from pydub import AudioSegment
            wav_path = output_path.replace(".mp3", ".wav")
            sound = AudioSegment.from_mp3(output_path)
            sound.export(wav_path, format="wav")
            print(f"Converted to WAV: {wav_path}")
            output_path = wav_path

        return output_path

    def play_audio(self, audio_path):
        """
        Play the audio file in the notebook
        """
        display(Audio(audio_path))
        return audio_path

# Usage example
def run_example():
    tts = TTSWrapper()

    # Example with English
    text_en = "Hello, this is a test of the text to speech system."
    audio_path_en = tts.synthesize(text_en, lang='en')
    tts.play_audio(audio_path_en)

    # Example with Kinyarwanda
    text_rw = "Muraho neza! Nishimiye kubabona."
    audio_path_rw = tts.synthesize(text_rw, lang='rw')
    tts.play_audio(audio_path_rw)

    return "TTS processing complete!"

# Alternative: Try to use the HuggingFace YourTTS model directly
def try_huggingface_yourtts():
    try:
        # Install the appropriate dependencies
        !pip install -q TTS
        from TTS.api import TTS

        # Initialize TTS with YourTTS
        tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=True)

        # Generate speech
        text = "Muraho neza! Nishimiye kubabona."
        output_path = "/content/yourtts_output.wav"

        # Generate with speaker embedding if possible
        tts.tts_to_file(text=text, file_path=output_path, speaker_wav=None, language="rw")

        # Play audio
        display(Audio(output_path))
        print(f"YourTTS audio saved to {output_path}")

        return "YourTTS processing complete!"
    except Exception as e:
        print(f"Error using YourTTS: {str(e)}")
        print("Falling back to gTTS")
        return run_example()

# Run the example (uncomment one of these lines)
run_example()
# try_huggingface_yourtts()